@files = (

 ['//property[propertyName="preamble"]/value' , 'preamble.pl'],
 ['//property[propertyName="KVM"]/value' , 'KVM.pm'],
 
 ['//procedure[procedureName="Create"]/step[stepName="Create"]/command' , 'vm/create.pl'],
 ['//procedure[procedureName="Create"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Start"]/step[stepName="Start"]/command' , 'vm/start.pl'],
 ['//procedure[procedureName="Start"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="ShutDown"]/step[stepName="ShutDown"]/command' , 'vm/shutdown.pl'],
 ['//procedure[procedureName="ShutDown"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Suspend"]/step[stepName="Suspend"]/command' , 'vm/suspend.pl'],
 ['//procedure[procedureName="Suspend"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Resume"]/step[stepName="Resume"]/command' , 'vm/resume.pl'],
 ['//procedure[procedureName="Resume"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 #['//procedure[procedureName="Reboot"]/step[stepName="Reboot"]/command' , 'vm/reboot.pl'],
 #['//procedure[procedureName="Reboot"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Destroy"]/step[stepName="Destroy"]/command' , 'vm/destroy.pl'],
 ['//procedure[procedureName="Destroy"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Clone"]/step[stepName="Clone"]/command' , 'vm/clone.pl'],
 ['//procedure[procedureName="Clone"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Snapshot"]/step[stepName="Snapshot"]/command' , 'vm/snapshot.pl'],
 ['//procedure[procedureName="Snapshot"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Revert"]/step[stepName="Revert"]/command' , 'vm/revert.pl'],
 ['//procedure[procedureName="Revert"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="Undefine"]/step[stepName="Undefine"]/command' , 'vm/undefine.pl'],
 ['//procedure[procedureName="Undefine"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="List"]/step[stepName="List"]/command' , 'vm/list.pl'],
 ['//procedure[procedureName="List"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="CleanUp"]/step[stepName="CleanUp"]/command' , 'vm/cleanup.pl'],
 ['//procedure[procedureName="CleanUp"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],
 ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="CreateResourceFromVM"]/command' , 'vm/createResourcesFromVM.pl'],
 ['//procedure[procedureName="CreateResourceFromVM"]/step[stepName="SetTimelimit"]/command' , 'setTimelimit.pl'],

 ['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'],
);
